Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  #approot: "http://localhost:3000"
  approot: "http://192.168.1.8:3000"
  copyright: Allan please add copyright statement here
  primaryColor: "#5677fc" # material blue 500
  accentColor: "#5af158" # material green A200
  votingWindow: 30
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://71.244.111.207:3000"
  <<: *defaults
