Default: &defaults
  database: psychic-bear.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: psychic-bear_test.sqlite3
  <<: *defaults

Staging:
  database: psychic-bear_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: psychic-bear_production.sqlite3
  poolsize: 100
  <<: *defaults
